resolver: lts-15.0
packages:
- tictactoe-server

extra-deps:
- Cabal-3.0.2.0
- HsYAML-0.2.1.0
- HsYAML-aeson-0.2.0.0
- process-1.6.10.0
- mtl-2.2.2
- transformers-0.5.6.2
- servant-0.16.2
- servant-auth-0.3.2.0
- servant-auth-server-0.4.5.0
- jose-0.8.3.1
- base64-bytestring-1.0.0.3
- stm-hamt-1.2.0.4
- stm-containers-1.1.0.4
- primitive-extras-0.8
- primitive-unlifted-0.1.3.0
- microlens-0.4.11.2

flags: {}

extra-package-dbs: []
